name: Deploy Golden Mask to Vercel

on:
  push:
    branches:
      - main # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Ensure compatibility with React 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Debug Vercel environment
      - name: Debug environment
        run: |
          echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}"
          echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}"
          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}" # Do not print in production for security reasons
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      # Step 5: Build the project
      - name: Build project
        run: npm run build

      # Step 6: Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod" # Use "--prod" for production deployments
          working-directory: . # Change this if your project is in a subfolder
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
