name: Deploy Golden mask to Vercel

on:
  push:
    branches:
      - main # Trigger deployment on pushes to the main branch
  pull_request: # Optional: Trigger on pull requests to preview deployments
    branches:
      - "*"

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies (if required)
      - name: Install dependencies
        run: npm install

      # Step 3: Build the project
      - name: Build project
        run: npm run build

      # Step 4: Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v21
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod" # Use "--prod" for production deployments
          working-directory: . # Change this if your project is in a subfolder
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
